comment: false
coverage:
  status:
    project: false
    patch:
      default:
        target: 80%
        threshold: 0%
        base: auto
        if_ci_failed: error
        paths:
          - "!nemo/collections/asr"
          - "!nemo/collections/audio"
          - "!nemo/collections/speechlm"
          - "!nemo/collections/tts"
          - "!nemo/core"
          - "!nemo/collections/common"
          - "!nemo/collections/multimodal_autoregressive"
          - "!nemo/collections/diffusion"
          - "!nemo/collections/nlp"

fixes:
  - "/workspace/::"
