# Regularly updates the CI container
name: MCore Tag Bump Bot
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  mcore:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_bump_dockerfile.yml@v0.11.0
    with:
      source-repository: NVIDIA/Megatron-LM
      source-ref: main
      build-arg: MCORE_TAG
      dockerfile: Dockerfile.ci
      base-branch: weekly-bump
      cicd-label: Run CICD
      pr-reviewers: 'pablo-garay'
    secrets:
      PAT: ${{ secrets.PAT }}
